POST  http://localhost:3003/api/blogs
Content-Type: application/json


{
    "title": "Harry Pottero",
    "author": "J.K. Rowling",
    "url": "hpandthedeadlyhallows.com",
    "likes": "10",
    "userId": "63d62e1c796d3931806bd2c4"
}